In [69]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [70]:
data=pd.read_csv(r"E:\python30Day\pandas\sales_prediction\myworld\sales_prediction.csv")

In [71]:
data

    Order Date Product Region  Sales  Quantity
0   2024-01-05  Laptop  North  50000         2
1   2024-01-10  Mobile  South  20000         3
2   2024-02-15  Tablet   East  15000         2
3   2024-02-20  Laptop   West  55000         1
4   2024-03-05  Mobile  North  22000         4
5   2024-03-18  Tablet  South  17000         2
6   2024-04-10  Laptop   East  60000         2
7   2024-04-22  Mobile   West  25000         3
8   2024-05-12  Tablet  North  18000         2
9   2024-05-25  Laptop  South  62000         1
10  2024-06-05  Mobile   East  27000         3
11  2024-06-18  Tablet   West  19000         2
12  2024-07-10  Laptop  North  65000         2
13  2024-07-22  Mobile  South  30000         4
14  2024-08-05  Tablet   East  20000         2
15  2024-08-18  Laptop   West  70000         1
16  2024-09-10  Mobile  North  32000         3
17  2024-09-25  Tablet  South  21000         2
18  2024-10-12  Laptop   East  72000         2
19  2024-10-28  Mobile   West  35000         4
20  2024-11-15  Tablet  North  22000         2
21  2024-11-30  Laptop  South  75000         1
22  2024-12-10  Mobile   East  37000         3
23  2024-12-20  Tablet   West  23000         2

In [72]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  24 non-null     str
 1   Product     24 non-null     str
 2   Region      24 non-null     str
 3   Sales       24 non-null     int64
 4   Quantity    24 non-null     int64
dtypes: int64(2), str(3)
memory usage: 1.1 KB

In [73]:
data.isnull().sum()

Order Date    0
Product       0
Region        0
Sales         0
Quantity      0
dtype: int64

In [74]:
data.drop_duplicates()

    Order Date Product Region  Sales  Quantity
0   2024-01-05  Laptop  North  50000         2
1   2024-01-10  Mobile  South  20000         3
2   2024-02-15  Tablet   East  15000         2
3   2024-02-20  Laptop   West  55000         1
4   2024-03-05  Mobile  North  22000         4
5   2024-03-18  Tablet  South  17000         2
6   2024-04-10  Laptop   East  60000         2
7   2024-04-22  Mobile   West  25000         3
8   2024-05-12  Tablet  North  18000         2
9   2024-05-25  Laptop  South  62000         1
10  2024-06-05  Mobile   East  27000         3
11  2024-06-18  Tablet   West  19000         2
12  2024-07-10  Laptop  North  65000         2
13  2024-07-22  Mobile  South  30000         4
14  2024-08-05  Tablet   East  20000         2
15  2024-08-18  Laptop   West  70000         1
16  2024-09-10  Mobile  North  32000         3
17  2024-09-25  Tablet  South  21000         2
18  2024-10-12  Laptop   East  72000         2
19  2024-10-28  Mobile   West  35000         4
20  2024-11-15  Tablet  North  22000         2
21  2024-11-30  Laptop  South  75000         1
22  2024-12-10  Mobile   East  37000         3
23  2024-12-20  Tablet   West  23000         2

In [75]:
data["Order Date"]=pd.to_datetime(data["Order Date"])

In [76]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  24 non-null     datetime64[us]
 1   Product     24 non-null     str
 2   Region      24 non-null     str
 3   Sales       24 non-null     int64
 4   Quantity    24 non-null     int64
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 1.1 KB

In [77]:
data['Month'] = data['Order Date'].dt.month

In [78]:
data['Year'] = data['Order Date'].dt.year

In [79]:
data.head(5)

  Order Date Product Region  Sales  Quantity  Month  Year
0 2024-01-05  Laptop  North  50000         2      1  2024
1 2024-01-10  Mobile  South  20000         3      1  2024
2 2024-02-15  Tablet   East  15000         2      2  2024
3 2024-02-20  Laptop   West  55000         1      2  2024
4 2024-03-05  Mobile  North  22000         4      3  2024

In [80]:
monthly_sales = data.groupby(['Year' , 'Month' ]) ['Sales'].sum().reset_index()

In [81]:
print(monthly_sales)

    Year  Month   Sales
0   2024      1   70000
1   2024      2   70000
2   2024      3   39000
3   2024      4   85000
4   2024      5   80000
5   2024      6   46000
6   2024      7   95000
7   2024      8   90000
8   2024      9   53000
9   2024     10  107000
10  2024     11   97000
11  2024     12   60000

In [88]:
print('\nTotal sales:', data['Sales'].sum())

Total sales: 892000

In [89]:
data.to_csv('clean_data.csv',index=False)

In [90]:
X = monthly_sales[['Month' , 'Year']]
Y = monthly_sales['Sales']

model = LinearRegression()
model.fit(X,Y)

future = pd.DataFrame({
    'Month' :[1,2,3,4,5,6,7],
    'Year' :[2026]*7
})
predictions = model.predict(future)
future['Predicted_Sales'] = predictions

print("\nFuture Sales Prediction")
print(future)

Future Sales Prediction
   Month  Year  Predicted_Sales
0      1  2026     64179.487179
1      2  2026     66025.641026
2      3  2026     67871.794872
3      4  2026     69717.948718
4      5  2026     71564.102564
5      6  2026     73410.256410
6      7  2026     75256.410256

In [87]:
future.to_csv("sales_forecast.csv", index=False)